# These are supported funding model platforms

github: [T-rustdev] 
patreon: T-rustdev-builds
open_collective: dillon-collective
ko_fi: T-rustdev
tidelift: npm/awesome-vibe-coding
community_bridge: awesome-vibe-coding
liberapay: T-rustdev
issuehunt: T-rustdev
lfx_crowdfunding: awesome-vibe-coding
polar: T-rustdev
buy_me_a_coffee: T-rustdev
thanks_dev: T-rustdev
custom: 
  - https://fnine.dev/sponsor
  - https://etherscan.io/address/0x240ACF16b5401E2EDb543B798aCA6BC3041b948d
