# These are supported funding model platforms

github: [T-rustdev] 
patreon: T-rustdev
custom: 
  - https://fnine.dev/sponsor
  - https://etherscan.io/address/0x240ACF16b5401E2EDb543B798aCA6BC3041b948d
